set define '&'
prompt Execute /database_directory/schema_directory_first/object_directory_second/dummy_s1_procedure_a.sql
@./database_directory/schema_directory_first/object_directory_second/dummy_s1_procedure_a.sql
prompt Execute /database_directory/schema_directory_first/object_directory_second/dummy_s1_procedure_b.sql
@./database_directory/schema_directory_first/object_directory_second/dummy_s1_procedure_b.sql
prompt Execute /database_directory/schema_directory_first/object_directory_second/dummy_s1_procedure_c.sql
@./database_directory/schema_directory_first/object_directory_second/dummy_s1_procedure_c.sql
