prompt Execute REUSABLE scripts with BEFORE condition.
prompt Execute /database_directory/schema_directory_second/script_directory_first/dummy_a.sql
@./database_directory/schema_directory_second/script_directory_first/dummy_a.sql
prompt Execute /database_directory/schema_directory_second/script_directory_first/dummy_b.sql
@./database_directory/schema_directory_second/script_directory_first/dummy_b.sql
prompt Execute /database_directory/schema_directory_second/script_directory_first/dummy_c.sql
@./database_directory/schema_directory_second/script_directory_first/dummy_c.sql
