set define '&'
prompt Execute /database_directory/schema_directory_first/object_directory_first/dummy_s1_function_a.sql
@./database_directory/schema_directory_first/object_directory_first/dummy_s1_function_a.sql
prompt Execute /database_directory/schema_directory_first/object_directory_first/dummy_s1_function_b.sql
@./database_directory/schema_directory_first/object_directory_first/dummy_s1_function_b.sql
prompt Execute /database_directory/schema_directory_first/object_directory_first/dummy_s1_function_c.sql
@./database_directory/schema_directory_first/object_directory_first/dummy_s1_function_c.sql
