\qecho Execute REUSABLE scripts with AFTER condition.
\qecho Execute /database_directory/public_script_directory_second/dummy_sp_reusable_after_a.sql
\include ./database_directory/public_script_directory_second/dummy_sp_reusable_after_a.sql
\qecho Execute /database_directory/public_script_directory_second/dummy_sp_reusable_after_b.sql
\include ./database_directory/public_script_directory_second/dummy_sp_reusable_after_b.sql
\qecho Execute /database_directory/public_script_directory_second/dummy_sp_reusable_after_c.sql
\include ./database_directory/public_script_directory_second/dummy_sp_reusable_after_c.sql
