\qecho Execute /database_directory/schema_directory_first/object_directory_first/dummy_s1_function_a.sql
\include ./database_directory/schema_directory_first/object_directory_first/dummy_s1_function_a.sql
\qecho Execute /database_directory/schema_directory_first/object_directory_first/dummy_s1_function_b.sql
\include ./database_directory/schema_directory_first/object_directory_first/dummy_s1_function_b.sql
\qecho Execute /database_directory/schema_directory_first/object_directory_first/dummy_s1_function_c.sql
\include ./database_directory/schema_directory_first/object_directory_first/dummy_s1_function_c.sql
