\qecho Execute /database_directory/public_object_directory_first/dummy_sp_function_a.sql
\include ./database_directory/public_object_directory_first/dummy_sp_function_a.sql
\qecho Execute /database_directory/public_object_directory_first/dummy_sp_function_b.sql
\include ./database_directory/public_object_directory_first/dummy_sp_function_b.sql
\qecho Execute /database_directory/public_object_directory_first/dummy_sp_function_c.sql
\include ./database_directory/public_object_directory_first/dummy_sp_function_c.sql
