prompt Execute REUSABLE scripts with AFTER condition.
prompt Execute /database/schema_second/script_reusable_after/dummy_s2_reusable_after_a.sql
@./database/schema_second/script_reusable_after/dummy_s2_reusable_after_a.sql
prompt Execute /database/schema_second/script_reusable_after/dummy_s2_reusable_after_b.sql
@./database/schema_second/script_reusable_after/dummy_s2_reusable_after_b.sql
prompt Execute /database/schema_second/script_reusable_after/dummy_s2_reusable_after_c.sql
@./database/schema_second/script_reusable_after/dummy_s2_reusable_after_c.sql
